jobs:

  ##########################
  # begin check_queue job
  ##########################
  - name: check_prod_queue
    type: runSh
    steps:
      - IN: check_queue_trigger
      - IN: config_repo
        switch: off
      - IN: prod_api_params
      - TASK:
        - script: ./IN/config_repo/gitRepo/checkQueue.sh prod
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('
      - NOTIFY: slack_prod

  ##########################
  # end check_queue job
  ##########################


  ###########################################
  # release production from default manifest
  ###########################################

  - name: rel_prod
    type: release
    steps:
      - IN: ship_ver
        switch: off
#      - IN: bvt-v2
#        switch: off
      - IN: rc_deploy  #temp instead of bvt-v2
        switch: off
      - TASK: managed
        bump: patch

  ###########################################
  # BEGIN run infra provisioning
  ###########################################

  - name: rc_saas_infra_prov
    type: runSh
    steps:
      - IN: aws_rc_pem
      - IN: aws_v2_rc_access
      - IN: infra_repo
        switch: off
      - TASK:
        - script: IN/infra_repo/gitRepo/provision.sh rc saas
    on_success:
      - script: echo 'SUCCESS!'
    on_failure:
      - script: echo 'FAILURE!'
    always:
      - script: /build/IN/infra_repo/gitRepo/archiveProvisionState.sh rc saas

  - name: prod_saas_infra_prov
    type: runSh
    steps:
      - IN: aws_prod_pem
      - IN: aws_v2_prod_access
      - IN: infra_repo
        switch: off
      - TASK:
        - script: IN/infra_repo/gitRepo/provision.sh prod saas
    on_success:
      - script: echo 'SUCCESS!'
    on_failure:
      - script: echo 'FAILURE!'
    always:
      - script: /build/IN/infra_repo/gitRepo/archiveProvisionState.sh prod saas

  ###########################################
  # BEGIN run infra provisioning
  ###########################################

  ###########################################
  # BEGIN Build Acceptance Tests
  ###########################################
  - name: bvt-v2
    type: runSh
    steps:
      - IN: bvt_v2_repo
      - IN: bvt_v2_params
      - IN: bvt_v2_ghc_owner_ssh_key
      - IN: bvt_v2_ghc_collab_ssh_key
#      - IN: deploy_rc
      - TASK:
        - script: IN/bvt_v2_repo/gitRepo/test.sh bvt_v2_params
    on_success:
      - NOTIFY: slack_rc
    on_failure:
      - NOTIFY: slack_rc
  ###########################################
  # END Build Acceptance Tests
  ###########################################
